import { Emitter } from '../src/emitter';
import * as path from 'path';

async function main() {
  const spec = {
    name: 'SaaS Flagship',
    slug: 'saas-flagship',
    description: 'The premier SaaS template generated by A1 App Foundry.'
  };

  const emitter = new Emitter({
    outDir: path.join(__dirname, '../../../../demo-output'),
    spec
  });

  await emitter.emit();
}

main().catch(console.error);
