const fs = require('fs-extra');
const path = require('path');
// Since we can't easily import TS in Node here without setup,
// I'll replicate the Emitter logic in JS for this demo to prove it works with the TEMPLATES.
const Handlebars = require('handlebars');

async function emitDir(src, dest, context) {
  const items = await fs.readdir(src);
  for (const item of items) {
    const srcPath = path.join(src, item);
    const stats = await fs.stat(srcPath);
    if (stats.isDirectory()) {
      const destPath = path.join(dest, item);
      await fs.ensureDir(destPath);
      await emitDir(srcPath, destPath, context);
    } else if (item.endsWith('.hbs')) {
      const targetName = item.slice(0, -4);
      const templateContent = await fs.readFile(srcPath, 'utf-8');
      const template = Handlebars.compile(templateContent);
      const result = template(context);
      await fs.outputFile(path.join(dest, targetName), result);
    }
  }
}

async function main() {
  const spec = {
    name: 'Luxury SaaS',
    slug: 'luxury-saas',
    description: 'A high-end SaaS platform generated by A1 Foundry.',
    entities: [
      { name: 'Customer', fields: [{ name: 'email', type: 'String', required: true }] },
      { name: 'Subscription', fields: [{ name: 'plan', type: 'String', required: true }] }
    ]
  };

  const templateDir = path.join(__dirname, '../packages/generator/src/templates');
  const outDir = path.join(__dirname, '../demo-output');

  await fs.ensureDir(outDir);
  await emitDir(templateDir, outDir, spec);
  console.log('Successfully emitted Luxury SaaS to demo-output');
}

main().catch(console.error);
