const fs = require('fs-extra');
const path = require('path');
const Handlebars = require('handlebars');

async function emitDir(src, dest, context) {
  const items = await fs.readdir(src);
  for (const item of items) {
    const srcPath = path.join(src, item);
    const stats = await fs.stat(srcPath);
    if (stats.isDirectory()) {
      const destPath = path.join(dest, item);
      await fs.ensureDir(destPath);
      await emitDir(srcPath, destPath, context);
    } else if (item.endsWith('.hbs')) {
      const targetName = item.slice(0, -4);
      const templateContent = await fs.readFile(srcPath, 'utf-8');
      const template = Handlebars.compile(templateContent);
      const result = template(context);
      await fs.outputFile(path.join(dest, targetName), result);
    }
  }
}

async function emitEntity(outDir, entity) {
  const backendSrc = path.join(outDir, 'backend/src');
  const content = `
import { Controller, Get, Post, Body } from '@nestjs/common';
import { PrismaService } from './prisma.service';

@Controller('${entity.name.toLowerCase()}s')
export class ${entity.name}Controller {
  constructor(private prisma: PrismaService) {}

  @Post()
  create(@Body() data: any) {
    return this.prisma.${entity.name.toLowerCase()}.create({ data });
  }

  @Get()
  findAll() {
    return this.prisma.${entity.name.toLowerCase()}.findMany();
  }
}
  `;
  await fs.outputFile(path.join(backendSrc, `${entity.name}.controller.ts`), content.trim());
}

async function main() {
  const spec = {
    name: 'Luxury SaaS',
    slug: 'luxury-saas',
    description: 'A high-end SaaS platform generated by A1 Foundry.',
    entities: [
      { name: 'Customer', fields: [{ name: 'email', type: 'String', required: true }] },
      { name: 'Subscription', fields: [{ name: 'plan', type: 'String', required: true }] }
    ]
  };

  const templateDir = path.join(__dirname, '../packages/generator/src/templates');
  const outDir = path.join(__dirname, '../demo-output');

  await fs.ensureDir(outDir);
  await emitDir(templateDir, outDir, spec);

  for (const entity of spec.entities) {
    await emitEntity(outDir, entity);
  }

  console.log('Successfully emitted Luxury SaaS to demo-output');
}

main().catch(console.error);
